config:
  git_user_name: CircleCI
  git_user_email: circleci@cureapp.jp
  npm_update_depth: 0
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: false
  create_gh_pages: false
  gh_pages_dir: doc
circle:
  machine:
    node:
      version: 6.3.1
